title: 'Data Science, Books and Other Musings'
description: A Blog by Callum Main

url: http://callummain.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: CallumMain
   twitter: CallumHMain
   linkedin: CallumMain
   email: CallumMain@gmail.com

#google_analytics: "UA-58263416-1"
